// Mocks generated by Mockito 5.4.6 from annotations
// in expense_tracker/test/budget_rollover_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:expense_tracker/budget_repository.dart' as _i2;
import 'package:expense_tracker/domain/entities/budget.dart' as _i4;
import 'package:expense_tracker/domain/entities/transaction.dart' as _i6;
import 'package:expense_tracker/domain/entities/trend_data_point.dart' as _i7;
import 'package:expense_tracker/features/transactions/domain/transaction_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BudgetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetRepository extends _i1.Mock implements _i2.BudgetRepository {
  MockBudgetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Budget>> watchAllBudgets() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllBudgets, []),
            returnValue: _i3.Stream<List<_i4.Budget>>.empty(),
          )
          as _i3.Stream<List<_i4.Budget>>);

  @override
  _i3.Future<void> addBudget(_i4.Budget? budget) =>
      (super.noSuchMethod(
            Invocation.method(#addBudget, [budget]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateBudget(_i4.Budget? budget) =>
      (super.noSuchMethod(
            Invocation.method(#updateBudget, [budget]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteBudget(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBudget, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i5.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i6.Transaction>> watchTransactionsInMonth(DateTime? month) =>
      (super.noSuchMethod(
            Invocation.method(#watchTransactionsInMonth, [month]),
            returnValue: _i3.Stream<List<_i6.Transaction>>.empty(),
          )
          as _i3.Stream<List<_i6.Transaction>>);

  @override
  _i3.Stream<List<_i6.Transaction>> watchRecentTransactions({
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchRecentTransactions, [], {#limit: limit}),
            returnValue: _i3.Stream<List<_i6.Transaction>>.empty(),
          )
          as _i3.Stream<List<_i6.Transaction>>);

  @override
  _i3.Stream<List<_i6.Transaction>> watchAllTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllTransactions, []),
            returnValue: _i3.Stream<List<_i6.Transaction>>.empty(),
          )
          as _i3.Stream<List<_i6.Transaction>>);

  @override
  _i3.Future<List<_i7.TrendDataPoint>> getMonthlyTrend(int? months) =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlyTrend, [months]),
            returnValue: _i3.Future<List<_i7.TrendDataPoint>>.value(
              <_i7.TrendDataPoint>[],
            ),
          )
          as _i3.Future<List<_i7.TrendDataPoint>>);

  @override
  _i3.Future<(double, double)> getMonthlySummaryTotals(DateTime? month) =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlySummaryTotals, [month]),
            returnValue: _i3.Future<(double, double)>.value((0.0, 0.0)),
          )
          as _i3.Future<(double, double)>);

  @override
  _i3.Future<void> addTransaction(_i6.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#addTransaction, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTransaction(_i6.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
