import 'package:flutter/material.dart';
import 'package:material_symbols_icons/symbols.dart';

IconData iconFromCodePoint(int codePoint) {
  if (codePoint == Symbols.restaurant.codePoint) return Symbols.restaurant;
  if (codePoint == Symbols.coffee.codePoint) return Symbols.coffee;
  if (codePoint == Symbols.local_bar.codePoint) return Symbols.local_bar;
  if (codePoint == Symbols.fastfood.codePoint) return Symbols.fastfood;
  if (codePoint == Symbols.shopping_bag.codePoint) return Symbols.shopping_bag;
  if (codePoint == Symbols.shopping_cart.codePoint) return Symbols.shopping_cart;
  if (codePoint == Symbols.store.codePoint) return Symbols.store;
  if (codePoint == Symbols.checkroom.codePoint) return Symbols.checkroom;
  if (codePoint == Symbols.local_gas_station.codePoint) return Symbols.local_gas_station;
  if (codePoint == Symbols.directions_car.codePoint) return Symbols.directions_car;
  if (codePoint == Symbols.directions_bus.codePoint) return Symbols.directions_bus;
  if (codePoint == Symbols.two_wheeler.codePoint) return Symbols.two_wheeler;
  if (codePoint == Symbols.build.codePoint) return Symbols.build;
  if (codePoint == Symbols.receipt_long.codePoint) return Symbols.receipt_long;
  if (codePoint == Symbols.electric_bolt.codePoint) return Symbols.electric_bolt;
  if (codePoint == Symbols.water_drop.codePoint) return Symbols.water_drop;
  if (codePoint == Symbols.wifi.codePoint) return Symbols.wifi;
  if (codePoint == Symbols.phone_android.codePoint) return Symbols.phone_android;
  if (codePoint == Symbols.home_repair_service.codePoint) return Symbols.home_repair_service;
  if (codePoint == Symbols.medical_services.codePoint) return Symbols.medical_services;
  if (codePoint == Symbols.fitness_center.codePoint) return Symbols.fitness_center;
  if (codePoint == Symbols.spa.codePoint) return Symbols.spa;
  if (codePoint == Symbols.health_and_safety.codePoint) return Symbols.health_and_safety;
  if (codePoint == Symbols.flight.codePoint) return Symbols.flight;
  if (codePoint == Symbols.hotel.codePoint) return Symbols.hotel;
  if (codePoint == Symbols.explore.codePoint) return Symbols.explore;
  if (codePoint == Symbols.school.codePoint) return Symbols.school;
  if (codePoint == Symbols.book.codePoint) return Symbols.book;
  if (codePoint == Symbols.movie.codePoint) return Symbols.movie;
  if (codePoint == Symbols.sports_esports.codePoint) return Symbols.sports_esports;
  if (codePoint == Symbols.music_note.codePoint) return Symbols.music_note;
  if (codePoint == Symbols.subscriptions.codePoint) return Symbols.subscriptions;
  if (codePoint == Symbols.home.codePoint) return Symbols.home;
  if (codePoint == Symbols.apartment.codePoint) return Symbols.apartment;
  if (codePoint == Symbols.child_care.codePoint) return Symbols.child_care;
  if (codePoint == Symbols.group.codePoint) return Symbols.group;
  if (codePoint == Symbols.pets.codePoint) return Symbols.pets;
  if (codePoint == Symbols.card_giftcard.codePoint) return Symbols.card_giftcard;
  if (codePoint == Symbols.volunteer_activism.codePoint) return Symbols.volunteer_activism;
  if (codePoint == Symbols.payments.codePoint) return Symbols.payments;
  if (codePoint == Symbols.trending_up.codePoint) return Symbols.trending_up;
  if (codePoint == Symbols.savings.codePoint) return Symbols.savings;
  if (codePoint == Symbols.monetization_on.codePoint) return Symbols.monetization_on;
  if (codePoint == Symbols.credit_card.codePoint) return Symbols.credit_card;
  if (codePoint == Symbols.account_balance.codePoint) return Symbols.account_balance;
  if (codePoint == Symbols.work.codePoint) return Symbols.work;
  if (codePoint == Symbols.celebration.codePoint) return Symbols.celebration;
  if (codePoint == Symbols.help.codePoint) return Symbols.help;
  return Icons.help_outline;
}
